import type { OverrideDef } from "./car-generation-overrides";

/** BMW — поколения как на Авито/Дром */
export const BMW_GENERATION_OVERRIDES: OverrideDef[] = [
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "1 Series",
    modelKeys: ["series1", "1erreihe", "1er"],
    modelSlugs: ["1-series", "series-1", "1er-reihe"],
    generations: [
      { code: "F70", yearFrom: 2024, yearTo: null, label: "F70" },
      { code: "F40", yearFrom: 2019, yearTo: 2024, label: "F40" },
      { code: "F20", yearFrom: 2011, yearTo: 2019, label: "F20" },
      { code: "E87", yearFrom: 2004, yearTo: 2011, label: "E87" },
      { code: "E81", yearFrom: 2004, yearTo: 2011, label: "E81" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "2 Series",
    modelKeys: ["series2", "2erreihe", "2er"],
    modelSlugs: ["2-series", "series-2", "2er-reihe"],
    generations: [
      { code: "G42", yearFrom: 2021, yearTo: null, label: "G42" },
      { code: "F22", yearFrom: 2014, yearTo: 2021, label: "F22" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "3 Series",
    modelKeys: ["series3", "3erreihe", "3er"],
    modelSlugs: ["3-series", "series-3", "3er-reihe"],
    generations: [
      { code: "G20", yearFrom: 2019, yearTo: null, label: "G20" },
      { code: "F30", yearFrom: 2012, yearTo: 2019, label: "F30" },
      { code: "E90", yearFrom: 2005, yearTo: 2012, label: "E90" },
      { code: "E46", yearFrom: 1998, yearTo: 2006, label: "E46" },
      { code: "E36", yearFrom: 1990, yearTo: 2000, label: "E36" },
      { code: "E30", yearFrom: 1982, yearTo: 1994, label: "E30" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "4 Series",
    modelKeys: ["series4", "4erreihe", "4er"],
    modelSlugs: ["4-series", "series-4", "4er-reihe"],
    generations: [
      { code: "G22", yearFrom: 2020, yearTo: null, label: "G22" },
      { code: "F32", yearFrom: 2013, yearTo: 2020, label: "F32" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "5 Series",
    modelKeys: ["series5", "5erreihe", "5er"],
    modelSlugs: ["5-series", "series-5", "5er-reihe"],
    generations: [
      { code: "G60", yearFrom: 2023, yearTo: null, label: "G60" },
      { code: "G30", yearFrom: 2017, yearTo: 2023, label: "G30" },
      { code: "F10", yearFrom: 2010, yearTo: 2017, label: "F10" },
      { code: "E60", yearFrom: 2003, yearTo: 2010, label: "E60" },
      { code: "E39", yearFrom: 1995, yearTo: 2004, label: "E39" },
      { code: "E34", yearFrom: 1988, yearTo: 1996, label: "E34" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "6 Series",
    modelKeys: ["series6", "6erreihe", "6er"],
    modelSlugs: ["6-series", "series-6", "6er-reihe"],
    generations: [
      { code: "G32", yearFrom: 2017, yearTo: 2023, label: "G32" },
      { code: "F06", yearFrom: 2011, yearTo: 2017, label: "F06" },
      { code: "E63", yearFrom: 2003, yearTo: 2010, label: "E63" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "7 Series",
    modelKeys: ["series7", "7erreihe", "7er"],
    modelSlugs: ["7-series", "series-7", "7er-reihe"],
    generations: [
      { code: "G70", yearFrom: 2022, yearTo: null, label: "G70" },
      { code: "G11", yearFrom: 2015, yearTo: 2022, label: "G11" },
      { code: "F01", yearFrom: 2008, yearTo: 2015, label: "F01" },
      { code: "E65", yearFrom: 2001, yearTo: 2008, label: "E65" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "8 Series",
    modelKeys: ["series8", "8erreihe", "8er", "8"],
    modelSlugs: ["8-series", "series-8", "8er-reihe"],
    generations: [
      { code: "G15 FL", yearFrom: 2022, yearTo: null, label: "II (G15) рестайлинг" },
      { code: "G15", yearFrom: 2018, yearTo: 2022, label: "II (G15)" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X1",
    modelKeys: ["x1"],
    modelSlugs: ["x1"],
    generations: [
      { code: "U11", yearFrom: 2022, yearTo: null, label: "U11" },
      { code: "F48", yearFrom: 2015, yearTo: 2022, label: "F48" },
      { code: "E84", yearFrom: 2009, yearTo: 2015, label: "E84" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X2",
    modelKeys: ["x2"],
    modelSlugs: ["x2"],
    generations: [
      { code: "U10", yearFrom: 2023, yearTo: null, label: "U10" },
      { code: "F39", yearFrom: 2017, yearTo: 2023, label: "F39" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X3",
    modelKeys: ["x3"],
    modelSlugs: ["x3"],
    generations: [
      { code: "G45", yearFrom: 2024, yearTo: null, label: "G45" },
      { code: "G01", yearFrom: 2017, yearTo: 2024, label: "G01" },
      { code: "F25", yearFrom: 2010, yearTo: 2017, label: "F25" },
      { code: "E83", yearFrom: 2003, yearTo: 2010, label: "E83" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X4",
    modelKeys: ["x4"],
    modelSlugs: ["x4"],
    generations: [
      { code: "G02", yearFrom: 2018, yearTo: null, label: "G02" },
      { code: "F26", yearFrom: 2014, yearTo: 2018, label: "F26" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X5",
    modelKeys: ["x5"],
    modelSlugs: ["x5"],
    generations: [
      { code: "G05", yearFrom: 2018, yearTo: null, label: "G05" },
      { code: "F15", yearFrom: 2013, yearTo: 2018, label: "F15" },
      { code: "E70", yearFrom: 2006, yearTo: 2013, label: "E70" },
      { code: "E53", yearFrom: 1999, yearTo: 2006, label: "E53" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X6",
    modelKeys: ["x6"],
    modelSlugs: ["x6"],
    generations: [
      { code: "G06", yearFrom: 2019, yearTo: null, label: "G06" },
      { code: "F16", yearFrom: 2014, yearTo: 2019, label: "F16" },
      { code: "E71", yearFrom: 2008, yearTo: 2014, label: "E71" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "X7",
    modelKeys: ["x7"],
    modelSlugs: ["x7"],
    generations: [
      { code: "G07", yearFrom: 2019, yearTo: null, label: "G07" },
    ],
  },
  {
    brand: "BMW",
    brandSlug: "bmw",
    modelName: "Z4",
    modelKeys: ["z4"],
    modelSlugs: ["z4"],
    generations: [
      { code: "G29", yearFrom: 2018, yearTo: null, label: "G29" },
      { code: "E89", yearFrom: 2009, yearTo: 2016, label: "E89" },
      { code: "E85", yearFrom: 2002, yearTo: 2008, label: "E85" },
    ],
  },
];
